[build]
  base = "."
  command = "pnpm install && cd apps/frontend && npx prisma generate --schema=../../packages/db/prisma/schema.prisma && npx next build"
  publish = "apps/frontend/.next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs" 